module.exports = {
  apps: [
    {
      name: "autoflow-api",
      cwd: "/var/www/autoFlow/apps/api",
      script: "pnpm",
      args: "start:prod",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "400M",
      env: { NODE_ENV: "production", PORT: 3000 },
      error_file: "/var/log/autoflow/api-error.log",
      out_file: "/var/log/autoflow/api-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "autoflow-frontend",
      cwd: "/var/www/autoFlow/apps/frontend",
      script: "pnpm",
      args: "start -p 3001",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "400M",
      env: { NODE_ENV: "production" },
      error_file: "/var/log/autoflow/frontend-error.log",
      out_file: "/var/log/autoflow/frontend-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
  ],
};
